"""Add security_question_2 and security_answer_hash_2 to users

Revision ID: 401fa6c2b3f4
Revises: b499e0edd2d9
Create Date: 2025-05-10 20:41:35.181139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401fa6c2b3f4'
down_revision = 'b499e0edd2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question_2', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('security_answer_hash_2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer_hash_2')
    op.drop_column('users', 'security_question_2')
    # ### end Alembic commands ###
