"""empty message

Revision ID: 413498bd35ff
Revises: e42f23e77645
Create Date: 2025-05-08 10:06:45.459018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413498bd35ff'
down_revision = 'e42f23e77645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
