"""Add default values for risk_level and other required fields

Revision ID: 8c02120848f1
Revises: 401fa6c2b3f4
Create Date: 2025-06-05 04:57:09.935191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c02120848f1'
down_revision = '401fa6c2b3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'risk_level')
    op.drop_column('users', 'security_answer_hash_2')
    op.drop_column('users', 'security_question_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question_2', sa.VARCHAR(length=200), nullable=True))
    op.add_column('users', sa.Column('security_answer_hash_2', sa.VARCHAR(length=128), nullable=True))
    op.add_column('transactions', sa.Column('risk_level', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
