"""Add profile_picture to users

Revision ID: b499e0edd2d9
Revises: 413498bd35ff
Create Date: 2025-05-10 11:42:51.822914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b499e0edd2d9'
down_revision = '413498bd35ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(length=120), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
